async function message(type, payload = {}) { return chrome.runtime.sendMessage({ type, ...payload }); }
const svg = document.querySelector('#tree'); const sessionSelect = document.querySelector('#session-select'); const detail = document.querySelector('#branch-detail'); const careDialog = document.querySelector('#care-dialog'); const careTitle = document.querySelector('#care-dialog-title'); const careCopy = document.querySelector('#care-dialog-copy'); const careCancel = document.querySelector('#care-cancel'); const careConfirm = document.querySelector('#care-confirm');
let selectedSessionId = null; let selectedNodeId = null; let careAction = null; let careReturnFocus = null;
function esc(v) { return String(v || '').replace(/[&<>\'\"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
function branchClass(node) { return node.state === 'pruned' ? 'pruned' : node.state === 'composted' ? 'saved' : node.depth >= 5 ? 'deep' : node.depth >= 4 ? 'long' : node.depth === 0 ? 'root' : 'healthy'; }
function nodeClasses(node) { return `${branchClass(node)}${node.closedAt ? ' closed' : ''}`; }
function confidenceLabel(node) { return node.relationshipConfidence === 'direct' ? 'direct link' : node.relationshipConfidence === 'tab-inferred' ? 'new tab from a tracked page' : 'unlinked path'; }
function nodeDescription(node) { const state = node.state === 'pruned' ? 'pruned and kept in the trail' : node.state === 'composted' ? 'resting in compost' : node.depth === 0 ? 'mission root' : `${branchClass(node)} branch`; return `${(node.title || node.url || 'Untitled path').slice(0, 80)}, ${state}, ${confidenceLabel(node)}, depth ${node.depth}`; }
function shortLabel(node) { const value = (node.title || node.url || 'Untitled path').replace(/^https?:\/\//, ''); return value.length > 20 ? `${value.slice(0, 19)}…` : value; }
function labelMarkup(node, point, depthCounts) { const crowded = depthCounts[node.depth] > (node.depth === 1 ? 8 : node.depth === 2 ? 5 : 1); if (node.id !== selectedNodeId && (node.depth > 2 || (node.depth > 0 && crowded))) return ''; const anchor = point.x > 720 ? 'end' : 'start'; const x = anchor === 'end' ? point.x - 20 : point.x + 20; const y = node.depth === 0 ? point.y + 34 : point.y + 4; return `<text x="${x}" y="${y}" text-anchor="${anchor}" class="node-label">${esc(shortLabel(node))}</text>`; }
function layout(nodes) {
  const nodeMap = new Map(nodes.map(node => [node.id, node])); const root = nodes.find(node => node.depth === 0) || nodes[0]; const rootId = root?.id; const children = new Map(); const parentById = new Map();
  nodes.forEach(node => { if (!rootId || node.id === rootId) return; const parentId = nodeMap.has(node.parentId) && node.parentId !== node.id ? node.parentId : rootId; parentById.set(node.id, parentId); if (!children.has(parentId)) children.set(parentId, []); children.get(parentId).push(node); });
  const weights = new Map(); const weight = id => { if (weights.has(id)) return weights.get(id); const total = (children.get(id) || []).reduce((sum, child) => sum + weight(child.id), 0) || 1; weights.set(id, total); return total; };
  if (rootId) weight(rootId);
  const maxDepth = Math.max(0, ...nodes.map(node => node.depth || 0)); const mode = nodes.length <= 1 ? 'seed' : maxDepth <= 1 && nodes.length <= 5 ? 'sapling' : maxDepth <= 3 && nodes.length <= 14 ? 'canopy' : 'deep'; const config = { seed: { height: 230, baseY: 190, gap: 52 }, sapling: { height: 270, baseY: 225, gap: 70 }, canopy: { height: 360, baseY: 300, gap: 66 }, deep: { height: 430, baseY: 360, gap: Math.max(28, 300 / Math.max(1, maxDepth)) } }[mode]; const positions = new Map(); if (rootId) positions.set(rootId, { x: 450, y: config.baseY });
  function place(parentId, left, right, depth) { const list = children.get(parentId) || []; if (!list.length) return; const total = list.reduce((sum, child) => sum + weight(child.id), 0); let cursor = left; list.forEach(child => { const span = (right - left) * (weight(child.id) / total); const inset = Math.min(18, span * .14); const childLeft = cursor + inset; const childRight = cursor + span - inset; positions.set(child.id, { x: (childLeft + childRight) / 2, y: config.baseY - depth * config.gap }); place(child.id, childLeft, childRight, depth + 1); cursor += span; }); }
  if (rootId) place(rootId, 70, 830, 1);
  nodes.forEach((node, index) => { if (!positions.has(node.id)) { const parentId = parentById.get(node.id) || rootId; const parent = parentId && positions.get(parentId); positions.set(node.id, { x: parent ? parent.x : 450 + ((index % 5) - 2) * 44, y: parent ? parent.y - config.gap : config.baseY }); } });
  const depthCounts = nodes.reduce((counts, node) => { counts[node.depth] = (counts[node.depth] || 0) + 1; return counts; }, {}); return { positions, parentById, children, depthCounts, root, maxDepth, mode, height: config.height, baseY: config.baseY };
}
function branchWidth(node) { return Math.max(2.5, 7 - (node.depth * .7)); }
function leafMarkup(node, p, tree) { if (node.depth === 0) return `<circle cx="${p.x}" cy="${p.y}" r="17"/>`; if ((tree.children.get(node.id) || []).length) return `<circle cx="${p.x}" cy="${p.y}" r="7" class="junction-mark"/>`; const side = node.id.length % 2 ? -1 : 1; return `<path class="terminal-leaf" d="M${p.x} ${p.y + 7} C${p.x + side * 2} ${p.y - 4}, ${p.x + side * 16} ${p.y - 12}, ${p.x + side * 22} ${p.y - 5} C${p.x + side * 18} ${p.y + 6}, ${p.x + side * 7} ${p.y + 10}, ${p.x} ${p.y + 7} Z"/>`; }
function renderTree(session) {
  svg.innerHTML = '';
  if (!session || !session.nodes.length) { svg.dataset.treeMode = 'empty'; svg.setAttribute('viewBox', '0 0 900 300'); svg.innerHTML = '<g class="empty-garden"><path d="M450 244 C450 220 448 198 450 174" class="empty-trunk"/><path d="M450 183 C428 160 409 151 394 151" class="empty-sprig"/><path d="M450 174 C470 151 490 146 508 148" class="empty-sprig"/><path d="M382 147 C388 128 406 121 423 125 C416 143 402 152 382 147 Z" class="empty-leaf"/><path d="M483 143 C496 125 516 123 530 131 C519 147 503 151 483 143 Z" class="empty-leaf"/><path d="M374 249 Q450 224 526 249" class="empty-ground"/><circle cx="450" cy="250" r="12" class="empty-root"/><text x="450" y="281" text-anchor="middle" class="empty-tree">Plant a mission to grow your first garden.</text></g>'; detail.hidden = true; return; }
  const nodes = session.nodes.slice(); const tree = layout(nodes); svg.dataset.treeMode = tree.mode; svg.setAttribute('viewBox', `0 0 900 ${tree.height}`); const positions = tree.positions; const nodeMap = new Map(nodes.map(node => [node.id, node]));
  const lines = nodes.filter(node => node.id !== tree.root?.id).map(node => { const parentId = tree.parentById.get(node.id); const parent = positions.get(parentId); const point = positions.get(node.id); return parent && point ? `<path d="M${parent.x} ${parent.y - 8} C${parent.x} ${parent.y - 34}, ${point.x} ${point.y + 34}, ${point.x} ${point.y + 8}" class="branch-line ${nodeClasses(node)}" style="--branch-width:${branchWidth(node)}px"/>` : ''; }).join('');
  const groundY = Math.min(tree.height - 20, tree.baseY + 18); const rootPoint = tree.root && positions.get(tree.root.id); const trunk = rootPoint ? `<path d="M450 ${groundY} C450 ${groundY - 12} 450 ${tree.baseY + 16} ${rootPoint.x} ${rootPoint.y + 12}" class="tree-trunk"/><path d="M${rootPoint.x - 72} ${groundY + 2} Q${rootPoint.x} ${groundY - 22} ${rootPoint.x + 72} ${groundY + 2}" class="tree-ground"/>` : '';
  const marks = nodes.map(node => { const point = positions.get(node.id); const selected = node.id === selectedNodeId ? ' selected' : ''; return `<g class="node ${nodeClasses(node)}${selected}" tabindex="0" role="button" data-node-id="${esc(node.id)}" aria-label="${esc(nodeDescription(node))}"><title>${esc(nodeDescription(node))}</title>${leafMarkup(node, point, tree)}${labelMarkup(node, point, tree.depthCounts)}</g>`; }).join('');
  svg.innerHTML = `<title>Living ${tree.mode} tree of ${esc(session.mission)}</title><g class="tree-structure" aria-hidden="true">${trunk}</g>${lines}${marks}`; renderDetail(nodeMap.get(selectedNodeId), session);
}
function renderDetail(node, session) {
  if (!node) { detail.hidden = true; detail.innerHTML = ''; return; }
  detail.hidden = false; const isRoot = node.depth === 0; const isPruned = node.state === 'pruned' || node.state === 'composted'; const parent = session.nodes.find(candidate => candidate.id === node.parentId); const parentLabel = parent ? `From “${shortLabel(parent)}”` : isRoot ? 'This is the mission root.' : 'Arrived as an unlinked path.'; const stateLabel = node.state === 'pruned' ? 'pruned' : node.state === 'composted' ? 'resting in compost' : 'growing';
  detail.innerHTML = `<div class="detail-copy"><p class="eyebrow">SELECTED PATH</p><h3>${esc((node.title || node.url || 'Untitled path').slice(0, 72))}</h3><p class="detail-meta">Depth ${node.depth} · ${esc(confidenceLabel(node))} · ${stateLabel}</p><p class="detail-parent">${esc(parentLabel)}</p></div><div class="detail-actions">${isRoot ? '<span class="detail-note">The root stays with this mission.</span>' : isPruned ? '<span class="detail-note">This path remains in the trail for reflection.</span>' : '<button data-branch-action="prune" class="detail-button">Prune this path</button><button data-branch-action="compost" class="detail-button">Return to compost</button>'}<button data-branch-action="close" class="detail-button quiet">Leave it growing</button></div>`;
}
function readableEvent(e) { if (e.type === 'mission_started') return `Planted “${e.mission}”.`; if (e.type === 'origin_planted') return 'Found the root page for this mission.'; if (e.type === 'navigation') return `Followed a branch to “${(e.url || '').replace(/^https?:\/\//, '').slice(0, 48)}”.`; if (e.type === 'external_path') return `Arrived at an unlinked path: “${(e.url || '').replace(/^https?:\/\//, '').slice(0, 48)}”.`; if (e.type === 'tab_joined_path') return 'A duplicate tab joined a known path.'; if (e.type === 'return_to_path') return 'Returned to a path already growing in this garden.'; if (e.type === 'composted') return 'Saved an interesting branch for later.'; if (e.type === 'pruned') return 'Pruned a branch while keeping its trail note.'; if (e.type === 'mission_changed') return 'Let this garden rest and chose a new direction.'; if (e.type === 'mission_ended' && e.reason === 'browse_without_mission') return 'Set this mission down and continued without one.'; if (e.type === 'mission_ended') return 'Closed this garden for the day.'; return e.type.replaceAll('_', ' '); }
function renderEvents(session) { const box = document.querySelector('#events'); box.innerHTML = (session?.events || []).slice().reverse().map(e => `<div class="event"><span class="event-dot"></span><div><strong>${esc(readableEvent(e))}</strong><small>${new Date(e.at).toLocaleTimeString([], { hour:'numeric', minute:'2-digit' })}${e.depth != null ? ` · branch ${e.depth}` : ''}</small></div></div>`).join('') || '<p class="muted">Your trail notes will appear here.</p>'; }
function renderCompost(items) { const box = document.querySelector('#compost'); box.innerHTML = items?.map(item => `<div class="compost-item"><div><a href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">${esc(item.title)}</a><small>${new Date(item.savedAt).toLocaleDateString()} · from “${esc(item.mission)}”</small></div><button data-id="${esc(item.id)}">Remove</button></div>`).join('') || '<p class="muted">Your saved curiosities will rest here.</p>'; }
function renderSessions(sessions, activeId, currentId) { sessionSelect.innerHTML = sessions.length ? sessions.slice().sort((a,b) => (b.endedAt || b.startedAt) - (a.endedAt || a.startedAt)).map(s => `<option value="${esc(s.id)}">${esc(s.mission)}${s.id === activeId ? ' · active' : ''}</option>`).join('') : '<option>No gardens yet</option>'; sessionSelect.value = currentId || activeId || sessions[0]?.id || ''; }
async function render() { const snap = await message('GET_SNAPSHOT', { sessionId: selectedSessionId, includeHistory: true }); selectedSessionId = snap.session?.id || null; renderSessions(snap.state.sessions || [], snap.activeSessionId, selectedSessionId); const session = snap.session; const nodes = session?.nodes || []; if (!nodes.some(node => node.id === selectedNodeId)) selectedNodeId = null; document.querySelector('#mission').textContent = session ? `Mission: ${session.mission}` : 'A visual record of where your attention wandered today.'; const deepest = Math.max(0, ...nodes.map(node => node.depth)); const composted = nodes.filter(node => node.state === 'composted').length; const pruned = nodes.filter(node => node.state === 'pruned').length; const changed = session?.endReason === 'mission_changed'; const storyline = !session ? 'A clearing is ready whenever you are.' : changed ? 'You noticed a new direction and gave this garden a graceful ending.' : pruned ? `You grew ${nodes.length} pages and pruned ${pruned} path${pruned === 1 ? '' : 's'} without losing the trail.` : composted ? `You grew ${nodes.length} pages and returned ${composted} curiosit${composted === 1 ? 'y' : 'ies'} to the compost pile.` : deepest >= 4 ? `You grew ${nodes.length} pages and found a long branch worth noticing.` : `You grew ${nodes.length} pages from a single clear intention.`; document.querySelector('#storyline').textContent = storyline; document.querySelector('#weather-cue').textContent = session?.status === 'completed' ? 'Resting garden' : deepest >= 4 ? 'A little dusk' : nodes.length > 4 ? 'Fern light' : 'Soft light'; document.body.dataset.gardenState = session?.status === 'completed' ? 'resting' : 'growing'; renderTree(session); renderEvents(session); renderCompost(snap.state.compostItems); }
function closeCareDialog() { careDialog.hidden = true; const returnFocus = careReturnFocus; careAction = null; careReturnFocus = null; if (returnFocus && document.contains(returnFocus)) returnFocus.focus(); }
function openCareDialog(action, trigger) { careAction = action; careReturnFocus = trigger; const deletingAll = action === 'clear'; careTitle.textContent = deletingAll ? 'Clear every garden?' : 'Forget this garden?'; careCopy.textContent = deletingAll ? 'This removes all local gardens, trail notes, and saved curiosities from this device. Nothing is sent anywhere.' : 'This removes the selected garden from this device. Its saved curiosities remain in the compost pile unless you remove them separately.'; careConfirm.textContent = deletingAll ? 'Clear local data' : 'Forget garden'; careDialog.hidden = false; careConfirm.focus(); }
async function confirmCareAction() { const action = careAction; const sessionId = selectedSessionId; closeCareDialog(); if (action === 'forget' && sessionId) { await message('DELETE_SESSION', { sessionId }); selectedSessionId = null; selectedNodeId = null; render(); } else if (action === 'clear') { await message('CLEAR_DATA'); selectedSessionId = null; selectedNodeId = null; render(); } }
careCancel.addEventListener('click', closeCareDialog); careConfirm.addEventListener('click', confirmCareAction); careDialog.addEventListener('click', event => { if (event.target === careDialog) closeCareDialog(); });
document.addEventListener('keydown', event => { if (careDialog.hidden) return; if (event.key === 'Escape') { event.preventDefault(); closeCareDialog(); } if (event.key === 'Tab') { const focusables = [careCancel, careConfirm]; const index = focusables.indexOf(document.activeElement); if (event.shiftKey && index <= 0) { event.preventDefault(); focusables[focusables.length - 1].focus(); } else if (!event.shiftKey && index === focusables.length - 1) { event.preventDefault(); focusables[0].focus(); } } });
async function selectNode(nodeId, returnFocus = false) { selectedNodeId = nodeId; await render(); if (returnFocus && !detail.hidden) detail.focus({ preventScroll: true }); }
sessionSelect.addEventListener('change', () => { selectedSessionId = sessionSelect.value; selectedNodeId = null; render(); });
svg.addEventListener('click', event => { const node = event.target.closest?.('[data-node-id]'); if (node) selectNode(node.dataset.nodeId); });
svg.addEventListener('keydown', event => { const node = event.target.closest?.('[data-node-id]'); if (node && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); selectNode(node.dataset.nodeId, true); } });
detail.addEventListener('click', async event => { const action = event.target.dataset.branchAction; if (!action) return; if (action === 'close') { selectedNodeId = null; render(); return; } if (!selectedSessionId || !selectedNodeId) return; await message('PRUNE_NODE', { sessionId: selectedSessionId, nodeId: selectedNodeId, toCompost: action === 'compost' }); render(); });
document.querySelector('#compost').addEventListener('click', async event => { const id = event.target.dataset.id; if (id) { await message('DELETE_COMPOST', { id }); render(); } });
document.querySelector('#forget').addEventListener('click', event => { if (selectedSessionId) openCareDialog('forget', event.currentTarget); });
document.querySelector('#clear').addEventListener('click', event => openCareDialog('clear', event.currentTarget));
render();
